#!/usr/bin/env python3
"""
D1 → `terms.json` 익스포트 (W0c §3-6).

[ADR-0012](docs/adr/0012-content-canon-d1.md)가 D1을 콘텐츠 정본으로 올리면서 생긴 **부채를
갚는 스크립트**다. 그 ADR의 Negative에 이렇게 적혀 있다:

    "콘텐츠 변경이 코드 리뷰를 빠져나갈 수 있다. 완화 = 익스포트·커밋 의무이나,
     **이건 규율이지 강제 장치가 아니다.** 잊으면 정본에 백업이 없는 상태가 된다."

규율에는 실행 수단이 필요하다. 이 파일이 그 수단이고, `bundle-snapshot.json`이 잊었는지를
드러내는 장치다.

사용:
    cd ~/devetym-proxy && npm run db:local --silent \\
      "SELECT payload, prompt_version FROM entries WHERE origin='authored'" > /tmp/rows.json
    cd ~/devetym && python3 Scripts/db-expand/export_bundle.py --rows /tmp/rows.json

⚠️ **바이트 동일이 오라클이다.** "의미적 동일"로 느슨하게 잡으면 형식이 조금씩 흘러
   커밋마다 650줄짜리 diff가 나고, 그러면 아무도 diff를 안 읽어 리뷰 지점이 실제로 사라진다.
   현행 파일은 `json.dumps(indent=2, ensure_ascii=False)` + 끝 개행으로 정확히 재현된다(실측 09-01).

⚠️ **정렬은 `keyword` 원문 사전순이다 — 정규화 키가 아니다.** 실측상 현행 파일이 그렇고,
   D1은 순서를 보장하지 않으므로 여기서 다시 정렬해야 한다. 두 정렬은 다른 순서를 낸다
   (`aa-tree` < `aatree`는 원문 기준, 정규화하면 둘 다 `aatree`).

⚠️ **버전 2필드는 빼고 쓴다.** 번들 엔트리는 6필드다(§3-3 `authored_payload`가 실어 준
   `schemaVersion`·`promptVersion`은 D1 전용). 넣으면 왕복이 안 닫힌다.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from authored_version import BUNDLE_FIELDS, bundle_prompt_version  # noqa: E402

REPO = Path(__file__).resolve().parents[2]
BUNDLE = REPO / "shared/src/commonMain/composeResources/files/terms.json"
SNAPSHOT = Path(__file__).parent / "bundle-snapshot.json"

MARKER = "generated by Scripts/db-expand/export_bundle.py — terms.json을 직접 편집하지 마세요"


def log(msg: str = "") -> None:
    print(msg, file=sys.stderr)


def rows_to_entries(rows: list[dict]) -> tuple[list[dict], str]:
    """D1 행 → 번들 엔트리. 6필드만 · 원래 키 순서 · keyword 원문 사전순."""
    tags = {r["prompt_version"] for r in rows}
    if len(tags) != 1:
        raise SystemExit(f"FAIL — authored 행의 태그가 하나가 아니다: {sorted(tags)}")
    tag = tags.pop()

    entries = []
    for r in rows:
        p = json.loads(r["payload"])
        missing = [k for k in BUNDLE_FIELDS if k not in p]
        if missing:
            raise SystemExit(f"FAIL — payload에 {missing} 없음: {p.get('keyword')!r}")
        entries.append({k: p[k] for k in BUNDLE_FIELDS})

    entries.sort(key=lambda e: e["keyword"])
    return entries, tag


def serialize(entries: list[dict]) -> str:
    """현행 파일을 바이트 단위로 재현하는 유일한 형식(실측 09-01)."""
    return json.dumps(entries, indent=2, ensure_ascii=False) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--rows", type=Path, required=True, help="npm run db:local 출력 JSON")
    ap.add_argument("--out", type=Path, default=BUNDLE)
    ap.add_argument("--check", action="store_true", help="쓰지 않고 현행 파일과 비교만")
    args = ap.parse_args()

    raw = json.loads(args.rows.read_text(encoding="utf-8"))
    rows = raw[0]["results"] if isinstance(raw, list) else raw["results"]
    entries, tag = rows_to_entries(rows)
    text = serialize(entries)
    log(f"D1 authored {len(rows)}행 · 태그 {tag}")

    # ── 왕복 증명 ─────────────────────────────────────────────────────────────
    # D1이 "이 행들은 스냅샷 X에서 왔다"고 말하고, 되뽑은 파일이 다시 X로 해시된다.
    # 어긋나면 시딩과 익스포트 중 한쪽이 내용을 바꾼 것이다 — 조용히 넘어가면 안 된다.
    exported_tag = bundle_prompt_version(entries)
    if exported_tag != tag:
        raise SystemExit(
            f"FAIL — 왕복이 안 닫혔다. D1 태그 {tag} · 익스포트 결과 {exported_tag}"
        )
    log(f"  왕복 ✓ 익스포트 결과가 같은 센티널로 해시된다")

    if args.out.exists():
        current = args.out.read_text(encoding="utf-8")
        if current == text:
            log("  현행 파일과 바이트 동일 — 쓸 것 없음")
        else:
            log(f"  ⚠️ 현행 파일과 다르다 ({len(current)} → {len(text)} 바이트)")
            if args.check:
                raise SystemExit("FAIL — --check 모드에서 차이 발견")

    if args.check:
        log("PASS — --check")
        return 0

    args.out.write_text(text, encoding="utf-8")
    SNAPSHOT.write_text(
        json.dumps(
            {
                "_marker": MARKER,
                "sentinel": tag,
                "entries": len(entries),
                "source": "D1 devetym-cache entries WHERE origin='authored'",
                "bundle": str(args.out.relative_to(REPO)),
            },
            indent=2,
            ensure_ascii=False,
        )
        + "\n",
        encoding="utf-8",
    )
    log(f"  → {args.out.relative_to(REPO)} · {SNAPSHOT.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
