#!/usr/bin/env python3
"""
번들 650 → D1 `entries`·`aliases` 시딩 SQL (W0c §3-4).

**stdout = SQL · stderr = 증명 로그.** 그래서 `> seed.sql`로 받아도 충돌 집계가 눈에 남는다.
"충돌 0건"은 주장이 아니라 로그로 증명되어야 한다(§3 표 오라클) — 조용한 0은 정의가
어디선가 안 쓰인 것과 구별되지 않는다.

사용:
    python3 Scripts/db-expand/seed_d1.py > /tmp/authored-seed.sql
    cd ~/devetym-proxy && npx wrangler d1 execute devetym-cache-sandbox --local --file=/tmp/authored-seed.sql

⚠️ **--local 외의 대상을 갖지 않는다.** 이 스크립트는 SQL을 뱉기만 하고 어디에도 붙지 않는다.
   원격 적용은 §3-7이고 사람 판정이다.

⚠️ **번들을 프록시 repo로 복사하지 않는다.** 사본이 생기는 순간 ADR-0012가 없애려던
   드리프트가 그대로 돌아온다. 값을 만드는 쪽은 여기(파이프라인)고, 붓는 쪽만 프록시다.

설계 결정 셋:

1. **`ON CONFLICT DO NOTHING`을 쓴다** — authored가 generated를 이기는 규칙은 §3-5다.
   여기서 덮어쓰기를 섞으면 두 단계의 오라클이 엉킨다. 실측상 충돌이 0건이라
   이 단계에서는 아무것도 안 밀린다(밀리면 로그가 그걸 드러낸다).

2. **별칭은 SQL 안에서 entries를 확인한다** — 파이썬은 authored 650만 알고 D1에 이미 있는
   generated 18행을 모른다. `WHERE NOT EXISTS (SELECT 1 FROM entries …)`로 실행 시점에
   걸러야 Worker `insertAliases`(entries-우선)와 같은 규칙이 된다.

3. **`created_at`은 고정값** — 번들 커밋 시각. 실행할 때마다 달라지면 SQL 파일을 diff해서
   "내용이 바뀌었나"를 볼 수 없다. term_entry는 만료되지 않으므로(INV-2) 이 값은 TTL에
   쓰이지 않는다 — 기록으로서의 의미만 있다.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from authored_version import (  # noqa: E402
    SCHEMA_VERSION,
    authored_payload,
    bundle_prompt_version,
    validate_authored,
)
from term_key import normalize_term_key  # noqa: E402

REPO = Path(__file__).resolve().parents[2]
BUNDLE = REPO / "shared/src/commonMain/composeResources/files/terms.json"

# 번들 terms.json의 커밋 시각(e8e04a8, 2026-07-05T02:02:44+09:00)을 UTC로.
BUNDLE_CREATED_AT = "2026-07-04T17:02:44.000Z"


def q(v) -> str:
    """SQL 문자열 리터럴. 작은따옴표만 이스케이프하면 된다(SQLite)."""
    return "'" + str(v).replace("'", "''") + "'"


def log(msg: str = "") -> None:
    print(msg, file=sys.stderr)


def build(entries: list[dict], created_at: str) -> tuple[list[str], int]:
    tag = bundle_prompt_version(entries)
    log(f"번들 {len(entries)}건 · 센티널 {tag}")

    # ── 게이트 ────────────────────────────────────────────────────────────────
    invalid = [(e.get("keyword"), p) for e in entries if (p := validate_authored(e))]
    if invalid:
        for k, p in invalid[:10]:
            log(f"  ✗ 부적합 {k!r}: {'; '.join(p)}")
        raise SystemExit(f"FAIL — 부적합 엔트리 {len(invalid)}건. 시딩 중단")
    log(f"  게이트 통과 {len(entries)}/{len(entries)}")

    # ── 1패스: entries ────────────────────────────────────────────────────────
    by_key: dict[str, list[str]] = {}
    for e in entries:
        by_key.setdefault(normalize_term_key(e["keyword"]), []).append(e["keyword"])

    pk_collisions = {k: v for k, v in by_key.items() if len(v) > 1}
    log(f"  entries 고유 키 {len(by_key)} · PK 충돌 {len(pk_collisions)}")
    for k, v in list(pk_collisions.items())[:10]:
        log(f"  ✗ PK 충돌 {k!r} ← {v}")
    if pk_collisions:
        raise SystemExit("FAIL — PK 충돌은 행 소실이다. 시딩 중단")

    out = [
        "-- generated by Scripts/db-expand/seed_d1.py — 직접 편집 금지",
        f"-- 번들 스냅샷 {tag} · {len(entries)}행 · 로컬 전용",
    ]
    for e in entries:
        payload = json.dumps(authored_payload(e, tag), ensure_ascii=False, sort_keys=True)
        out.append(
            "INSERT INTO entries (term_key, branch, payload, prompt_version, "
            "schema_version, created_at, hit_count, origin) VALUES ("
            f"{q(normalize_term_key(e['keyword']))}, 'term_entry', {q(payload)}, "
            f"{q(tag)}, {SCHEMA_VERSION}, {q(created_at)}, 0, 'authored') "
            "ON CONFLICT(term_key) DO NOTHING;"
        )

    # ── 2패스: aliases (entries-우선) ─────────────────────────────────────────
    entry_keys = set(by_key)
    claimed: dict[str, str] = {}
    shadowed_by_entry = 0   # 별칭 키가 어떤 엔트리의 keyword와 같다 → 안 넣는다
    self_fold = 0           # 같은 엔트리의 별칭 둘이 한 키로 접힘 → 무해
    cross_entry: list[tuple[str, str, str]] = []  # 엔트리간 충돌 → first-write-wins

    alias_rows: list[tuple[str, str]] = []
    for e in entries:
        term_key = normalize_term_key(e["keyword"])
        for alias in e.get("aliases", []):
            ak = normalize_term_key(alias)
            if not ak or ak in entry_keys:
                shadowed_by_entry += 1
                continue
            if ak in claimed:
                if claimed[ak] == term_key:
                    self_fold += 1
                else:
                    cross_entry.append((ak, claimed[ak], term_key))
                continue
            claimed[ak] = term_key
            alias_rows.append((ak, term_key))

    log(f"  aliases 삽입 대상 {len(alias_rows)}")
    log(f"    엔트리 키에 가려짐 {shadowed_by_entry} · 자기접힘 {self_fold}")
    log(f"    엔트리간 충돌 {len(cross_entry)} (first-write-wins)")
    for ak, win, lose in cross_entry:
        log(f"      · {ak!r}: {win} 유지 / {lose} 버림")

    out.append("-- aliases: entries FK를 참조하므로 반드시 뒤에 온다.")
    out.append("-- WHERE NOT EXISTS = Worker insertAliases의 entries-우선 규칙. 파이썬이 모르는")
    out.append("--   기존 generated 18행의 term_key까지 실행 시점에 걸러 준다.")
    for ak, tk in alias_rows:
        out.append(
            f"INSERT INTO aliases (alias_key, term_key) SELECT {q(ak)}, {q(tk)} "
            f"WHERE NOT EXISTS (SELECT 1 FROM entries WHERE term_key = {q(ak)}) "
            "ON CONFLICT(alias_key) DO NOTHING;"
        )

    return out, len(alias_rows)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--bundle", type=Path, default=BUNDLE)
    ap.add_argument("--created-at", default=BUNDLE_CREATED_AT)
    args = ap.parse_args()

    entries = json.loads(args.bundle.read_text(encoding="utf-8"))
    sql, n_alias = build(entries, args.created_at)
    print("\n".join(sql))
    log()
    log(f"기대값 — 이 SQL 적용 후: entries += {len(entries)} · aliases += 최대 {n_alias}")
    log("        (별칭 일부는 기존 generated 엔트리 키에 가려져 실행 시점에 더 줄 수 있다)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
